repos:
  - repo: local
    hooks:
      - id: sort-txt-file
        name: Sort text file alphabetically
        entry: python scripts/sort_txt.py
        language: system
        files: blocked_domains\.txt$
        pass_filenames: true

      - id: sort-json-files
        name: Sort JSON files alphabetically
        entry: python scripts/sort_json.py
        language: system
        files: \.json$
        pass_filenames: true